name: "publish"
on:
  push:
    branches:
      - main 
      - polishing_and_testing 

permissions:
  contents: write
  actions: write

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    env:
      working-directory: ./crates/bar-factory

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 22 
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ../target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: oven-sh/setup-bun@v2
      - name: install app dependencies and build it
        run: bun install && bun run build
        working-directory: ${{env.working-directory}}
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: bar-factory-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Bar factory v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: true 
          projectPath: ${{env.working-directory}}
